### ISSUE TITLE
Figure out a good way to create a unique ID for reminders

### ISSUE THREAD

**Issue by AndrewHaddon74** [cs481-ekh/s22-ema#166]
Create a way to generate unique IDs for the reminders, there is already a way to tag each reminder with each the ID.

**Comment by alejandro-macias** [comment]
During my research, I was able to find a library to generate these unique IDs. It will involve a function to generate these ids as well as check our backup reminder table in firebase to prevent duplicate IDs. I will go ahead and implement it and link to to this research/task.
