### ISSUE TITLE
Add a tag to notification to show which project the notification is associated with

### ISSUE THREAD

**Issue by jasonkboise** [cs481-ekh/s22-ema#65]
References User Story #63

**Comment by jonytipton** [comment]
Need to discuss implementation issues and place in Sprint2 backlog. FCM notification package does not include 'topic' data and Firebase Messaging functions do not include a "isSubscribed(to: Topic)". Have been attempting to follow steps here: [Request Topic with Relation Maps in App Instance](https://developers.google.com/instance-id/reference/server#get_information_about_app_instances). I think it would be better for the client to keep track of what topics they are subscribed to and add a screen that allows users to view and unsubscribe from topics. Haven't been able to think of a way to get the subscribed topic to link with notification being sent from Firebase console.
