### ISSUE TITLE
add a warning if project id doesn't exist

### ISSUE THREAD

**Issue by jasonkboise** [cs481-ekh/s22-ema#66]

**Comment by jonytipton** [comment]
Similar issue with adding projectID/Topic label to a notification. Need to discuss client side keeping track of topics. Attempted to get list of topics from firebase using REST APIs but ran into issues with null data in responses. I think using the REST APIs will be the solution but will need to integrate with the other issue of client keeping track of subscribed/unsubscribed topics.
